apiVersion: v1
kind: Secret
metadata:
  name: worker-secrets
type: Opaque
stringData:
  DATABASE_URL: ""
  REDIS_URL: ""

  REDIS_HOST: "host:port"
  REDIS_PASSWORD: ""
  REDIS_USERNAME: ""

  AWS_REGION: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  S3_BUCKET: ""