name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push SERVER to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/server/dockerfile
          push: true
          tags: harshitbreaksprod/the-index-server:${{ github.sha }}

      - name: Build and push WORKER to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/worker/dockerfile
          push: true
          tags: harshitbreaksprod/the-index-worker:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy docker-compose to vm
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "~/app/"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/app
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

            cat <<EOF > .env
            IMAGE_TAG=${{github.sha}}
            HTTP_PORT=${{secrets.HTTP_PORT}}
            FRONTEND_URL=${{secrets.FRONTEND_URL}}
            SALTROUNDS=${{secrets.SALTROUNDS}}
            JWT_SECRET=${{secrets.JWT_SECRET}}
            DATABASE_URL=${{secrets.DATABASE_URL}}
            REDIS_URL=${{secrets.REDIS_URL}}
            AWS_REGION=${{secrets.AWS_REGION}}
            AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}
            AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}
            S3_BUCKET=${{secrets.S3_BUCKET}}
            GEMINI_API_KEY=${{secrets.GEMINI_API_KEY}}
            OPENAI_API_KEY=${{secrets.OPENAI_API_KEY}}
            EOF

            docker compose pull
            docker compose up -d
